### PR TITLE
Docker container for CIVET-2.1.1

### PR DESCRIPTION
**Pull request by jennydaman**
I wrote a Dockerfile to compile CIVET-2.1.1 in an Ubuntu 18.04 container.
Docker enables the application to run on any host operating system. Moreover, some issues regarding "best practices" are handled by Docker such as isolation of the CIVET quarantine from the host system and providing scope to the environment variables set by init.sh.

perl and imagemagick are installed for `verify_clasp` and `verify_civet`. perl is a required dependency to run `CIVET_Processing_Pipeline` (this should be noted in [README.md](https://github.com/aces/CIVET_Full_Project/blob/master/README.md))

In the `builder` stage, git-lfs is installed and git is configured to use HTTPS instead of SSH for pulling repositories listed in [Makefile](https://github.com/aces/CIVET_Full_Project/blob/master/Makefile).
`netpbm-10.35.94` is decompressed early so that we can sideload a [Makefile.config](https://github.com/aces/CIVET_Full_Project/commit/4cdbc6513a0e372adf0354c8e434a43b5235e1a6#diff-7cb73d052e5b02d8416cc98746aae6ef). The provided Makefile.config was previously generated by following the directions from [README.md](https://github.com/aces/CIVET_Full_Project/blob/master/README.md#4---build-your-civet). Its presence before `./install.sh` tells `make` to skip `./configure`, making the entire script non-interactive.

https://github.com/aces/CIVET_Full_Project/blob/c934d28e6c557611c586b2f6c795c4ffe63c9bf7/Makefile#L1591-L1599

Using Docker multi-stage builds, the binaries are copied (without unnecessary build tools) to the base Ubuntu 18.04 image. The final image size is 3.05 GB (builder size was 9.74GB). Some build files are deleted, though I decided to keep `/include` for developers.

Finally, the function of init.sh is replicated using the ENV instruction. The shell is guaranteed to have the proper environment variables set, so it's possible to invoke CIVET binaries (e.g. `surface_fit`, `sphere_mesh`) directly from `docker run`.

```bash
docker build -t civet:2.1.1 $PWD
```

### CODE REVIEW

**Comment by gdevenyi** [comment]
Amazing work!

**Comment by prioux** [comment]
I am going to build this later this week and try it out

**Comment by sandywang** [comment]
Hi @jennydaman, great work! I will try to review and merge it and modify the README.md this week.
Thank you very much for the contribution!

Best,
Xindi

**Comment by prioux** [comment]
I am building this right now, and double checking everything.

I must say I really like your Dockerfile, @jennydaman , it's clean and the fact that you are using named stages (base and builder) really keep the resulting container quite clean.

**Comment by prioux** [comment]
What I want to make sure is that we can use this image to launch other tools that are build in it too, like any of the individual minc tools, and the CIVET_QC_Pipeline.

**Comment by jennydaman** [comment]
Thank you @prioux! 

Should be able to, e.g.

```
$ docker run --rm civet:2.1.1 surface_fit
Usage:     surface_fit  help not implemented yet

Copyright Alan C. Evans
Professor of Neurology
McGill University
```

```
docker run --rm -v "$PWD/mni_icbm_00100_t1.mnc:/v.mnc" civet:2.1.1 mincinfo /v.mnc
file: /v.mnc
image: signed__ short 0 to 4095
image dimensions: xspace zspace yspace
dimension name         length         step        start
--------------         ------         ----        -----
xspace                    170            1      -82.551
zspace                    256           -1      102.811
yspace                    256           -1      161.156
```

Of course, I ran the full `job_test` before this PR.

**Comment by prioux** [comment]
Yes, everything works fine. This is very good work, I approve the PR.

Do you prefer a Squash merge (with a single commit, but it would be detached from your fork and you'll have to delete the branch in force mode) or a normal merge (with 4 commits)?

**Review by prioux — APPROVED** [review]
All is fine.

**Comment by jennydaman** [comment]
You should squash it to shorten the log.

**Comment by prioux** [comment]
I'm going to push the image to Dockerhub as `mcin/civet:2.1.1`

**Comment by prioux** [comment]
DockerHub now has `mcin/civet:2.1.1` . This means it can also be used through Singularity, e.g. on the Compute Canada clusters.

**Comment by sandywang** [comment]
@Pierre Rioux, Mr <pierre.rioux@mcgill.ca>
Hi Pierre, did you create docker image on Mac OS, when I run docker
building on Linux, it failed at Step 22, multi-stage COPY
Step 22/25 : COPY --from=builder /opt/CIVET/Linux-x86_64/
/opt/CIVET/Linux-x86_64/
failed to copy files: failed to copy directory: Error processing tar
file(exit status 1): unexpected EOF
Is it a problem about the limitation of docker image size or some other
reason?

Best,
Xindi
--
Sincerely,
Xindi Wang

PhD,
Postdoctoral Researcher,
McGill Centre for Integrative Neuroscience (MCIN),
Montreal Neurological Institute (MNI),
3801 University St., Montreal, QC., Canada, H3A 2B4

**Comment by jennydaman** [comment]
@sandywang what version of Docker are you on? Multi-stage builds require 17.05 or higher.

https://docs.docker.com/develop/develop-images/multistage-build/

My docker version is `Docker version 19.03.5-ce, build 633a0ea838`

**Comment by prioux** [comment]
I replied to Xindi by email; our lab's docker development machine also has 19.03.5, and it builds the container just fine.

**Comment by sandywang** [comment]
Hi @*prioux*, @*jennydaman*
There may be one reason, all TGZ files in CIVET_Full_Project/TGZ need be
downloaded by using git lfs, did you just download CIVET_Full_Project by
using git lfs?
I would think DOCKER will install git-lfs in the docker image so that I
don't use git-lfs when I download CIVET_Full_Project. I will test again, if
yes, I would mention it in README
and commit it.

Best,
Xindi
--
Sincerely,
Xindi Wang

PhD,
Postdoctoral Researcher,
McGill Centre for Integrative Neuroscience (MCIN),
Montreal Neurological Institute (MNI),
3801 University St., Montreal, QC., Canada, H3A 2B4

**Comment by prioux** [comment]
@sandywang I don't understand. The Dockerfile is self contained, it has all the necessary code and tools to build itself, including git lfs. I think something else is the problem, I really suggest you let me have a look at how you're trying to build this.

**Pull request merged**
