### PR TITLE
Docker improvements

### PR DESCRIPTION
**Pull request by gdevenyi**
Two further improvements to dockerfile.

1. Slim down by using --no-install-recommends and gnuplot-nox.
2. Add running of the CIVET test suite so that future modifications to the build or Dockerfile get checked.

### CODE REVIEW

**Comment by sandywang** [comment]
Hi Gabriel, 
I agree the first modification.
For the second, I will merge it now. However, considering it costs several hours to run job_test. I will comment 'run job_test' and update README in the next release version to let user select whether test it or not.

Best,
Xindi

**Comment by gdevenyi** [comment]
@sandywang thanks, from my perspective, you guys are the ones who will build the container (typically) and it only happens once and goes up onto dockerhub for others to use.

Speaking of which @prioux would you please rebuild this version and push it up? This is the end of my changes to the Docker container for now.

**Comment by prioux** [comment]
yes, right away

**Comment by prioux** [comment]
The build is failing right at the start, in the first `apt-get install` (step 3). Not sure of it's a network problem or not... I'll try again in a few hours.

**Comment by prioux** [comment]
I think it's your recent `"--no-install-recommends"` that's breaking it

**Comment by prioux** [comment]
Nope, sorry, I tried without it and it fails the same way.

**Comment by prioux** [comment]
OK figured it out. Docker was caching an intermediate image for step 2 that doesn't allow step 3 to run anymore. I just had to clean up the docker overlays.

The container is building now.

**Comment by gdevenyi** [comment]
> OK figured it out. Docker was caching an intermediate image for step 2 that doesn't allow step 3 to run anymore. I just had to clean up the docker overlays.

Weird, that's not supposed to happen :)

**Comment by prioux** [comment]
It was because something has changed on the remote side (the debian repos), so the information stored locally during step 2 (apt-get update) was no longer good (package paths or version or something).

**Comment by prioux** [comment]
Right now the Docker build is running 'job_test', your new entry in the Dockerfile.

**Comment by gdevenyi** [comment]
> It was because something has changed on the remote side (the debian repos), so the information stored locally during step 2 (apt-get update) was no longer good (package paths or version or something).

Ah ha, that's exactly what I guessed :)

I classically write my Dockerfiles with ``apt-get update && apt-get install`` as a single command to avoid such issues.

**Comment by prioux** [comment]
Build was successful. The job_test took 25,000 seconds.

Pushing to DockerHub now, it should be ready in about 20 minutes.

**Pull request merged**
