### PR TITLE
Fix up spellings and standardize naming for Github

### PR DESCRIPTION
**Pull request by gdevenyi**

### CODE REVIEW

**Comment by sandywang** [comment]
Dear Dr. Devenyi,
In MakeFile, there are also three line we should copy License to build whole source code, binaries and packages:
Line   68: 	@cp -f -p License dist/
Line 142:	@cp -f -p License dist/
Line 222:	        License
Could you also modify them to LICENSE in this commit?

If you have no time, I will work on it in next commit, but you need also merge your fork after I push.
Thank you very much!

Best,
Xindi

**Comment by gdevenyi** [comment]
Cheers can do!

**Comment by sandywang** [comment]
Dear Dr. Devenyi,
Thank you very much! 
I will close this PR. As long as you update the LICENSE in MakeFile, you can make a new MR and I will merge it asap.

Best,
Xindi

**Comment by sandywang** [comment]
Close and wait for new PR including modification in MakeFile.

**Pull request merged**
