### PR TITLE
Add CIVET base directory to path in Dockerfile

### PR DESCRIPTION
**Pull request by gdevenyi**
Currently CIVET_Processing_Pipeline is not in PATH.

### CODE REVIEW

**Comment by gdevenyi** [comment]
Now that the singularity container works, I discover that PATH doesn't include the actual CIVET pipeline :)

**Comment by prioux** [comment]
Is it exactly how the init.sh file sets it up?

**Comment by gdevenyi** [comment]
init.sh doesn't add that directory to the PATH, which of course means you can only run CIVET by knowing the path its installed to and providing a full path. I've never seen that use in practice, it seems to always actually be in PATH. I guess this is an oversight in init.sh that one one bothered to fix in the packages but always just fixed post-hoc?

**Comment by prioux** [comment]
Hum. Weird. In CBRAIN I've always just invoked CIVET without a full, explicit path.

Anyway, this PR is fine with me too. @sandywang ?

**Comment by prioux** [comment]
I'll rebuild the container once both PRs are merged.

**Comment by gdevenyi** [comment]
@prioux I have one more fix to push to the container builds once these are merged

**Comment by prioux** [comment]
OK! :-)

**Comment by prioux** [comment]
Wow GitHub is having problems today. Whenever I refresh the page I get different icons for the authors of the messages here.

**Comment by gdevenyi** [comment]
I had issues today too, error 500 earlier on some repos.

**Pull request merged**
